from io import BytesIO
from typing import Any, Dict, List, Optional, cast
from datetime import datetime, date, time

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

try:
    import pandas as pd
except Exception:
    pd = None


def _safe_sheet_name(name: str) -> str:
    name = (name or "Sheet").strip()
    bad = ['\\', '/', '*', '[', ']', ':', '?']
    for b in bad:
        name = name.replace(b, "-")
    return name[:31] if len(name) > 31 else name


def _unique_sheet_name(wb: Workbook, desired: str) -> str:
    desired = _safe_sheet_name(desired)
    if desired not in wb.sheetnames:
        return desired

    base = desired
    i = 2
    while True:
        suffix = f" ({i})"
        candidate = _safe_sheet_name(base[: max(0, 31 - len(suffix))] + suffix)
        if candidate not in wb.sheetnames:
            return candidate
        i += 1


def _autosize(ws: Worksheet) -> None:
    for col_cells in ws.columns:
        col_cells = list(col_cells)
        if not col_cells:
            continue
        col_idx = cast(int, col_cells[0].column)
        col_letter = get_column_letter(col_idx)

        max_len = 0
        for cell in col_cells:
            v = "" if cell.value is None else str(cell.value)
            max_len = max(max_len, len(v))

        ws.column_dimensions[col_letter].width = min(max_len + 2, 60)


def _clean_excel_value(val: Any) -> Any:
    """
    Excel does not support timezone-aware datetime/time values.
    Convert timezone-aware values to naive values before writing.
    """
    if val is None:
        return ""

    if pd is not None and isinstance(val, pd.Timestamp):
        if val.tzinfo is not None:
            return val.tz_localize(None).to_pydatetime()
        return val.to_pydatetime()

    if pd is not None and val is pd.NaT:
        return ""

    if isinstance(val, datetime):
        if val.tzinfo is not None:
            return val.replace(tzinfo=None)
        return val

    if isinstance(val, time):
        if val.tzinfo is not None:
            return val.replace(tzinfo=None)
        return val

    if isinstance(val, (list, dict, set, tuple)):
        return str(val)

    return val


def render_xlsx(payload: dict) -> bytes:
    wb = Workbook()

    summary_ws = cast(Worksheet, wb.active)
    summary_ws.title = "Summary"

    meta = payload.get("meta", {}) or {}

    summary_ws["A1"] = "Report Summary"
    summary_ws["A1"].font = Font(size=14, bold=True)

    summary_ws.append([])
    summary_ws.append(["Title", _clean_excel_value(meta.get("title", ""))])
    summary_ws.append(["Generated At", _clean_excel_value(meta.get("generated_at", ""))])
    summary_ws.append(["Generated By", _clean_excel_value(meta.get("generated_by", ""))])
    summary_ws.append(["Report Type", _clean_excel_value(meta.get("report_type", "") or meta.get("module", ""))])

    report_type = str(meta.get("report_type", "")).strip().lower()

    if report_type == "exhibitor":
        summary_ws.append(["Event", _clean_excel_value(meta.get("event_name", meta.get("event_id", "")))])
        summary_ws.append(["Exhibitor", _clean_excel_value(meta.get("exhibitor_name", meta.get("exhibitor_id", "")))])
        summary_ws.append(["Booth(s)", _clean_excel_value(meta.get("booths", ""))])
        summary_ws.append(["Hall(s)", _clean_excel_value(meta.get("halls", ""))])
    else:
        summary_ws.append(["Zones", _clean_excel_value(meta.get("zones", ""))])
        summary_ws.append(["Facilities", _clean_excel_value(meta.get("facilities", ""))])

    summary_ws.append(["Date From", _clean_excel_value(meta.get("date_from", ""))])
    summary_ws.append(["Date To", _clean_excel_value(meta.get("date_to", ""))])
    summary_ws.append(["Aggregation Level", _clean_excel_value(meta.get("aggregation_level", ""))])
    summary_ws.append([])

    summary_ws.append(["Data Sheets"])
    summary_ws["A{}".format(summary_ws.max_row)].font = Font(bold=True)

    xlsx_obj = payload.get("xlsx", {}) or {}
    sheets = xlsx_obj.get("sheets") or []
    sheet_registry = []

    for sh in sheets:
        columns = sh.get("columns") or []
        rows = sh.get("rows") or []

        if not columns:
            continue

        sheet_name = _unique_sheet_name(wb, sh.get("name", "Sheet"))
        ws = wb.create_sheet(sheet_name)

        for col_idx, col in enumerate(columns, start=1):
            cell = ws.cell(row=1, column=col_idx, value=_clean_excel_value(col))
            cell.font = Font(bold=True)

        for r in rows:
            if isinstance(r, dict):
                ws.append([_clean_excel_value(r.get(col, "")) for col in columns])
            else:
                ws.append(["" for _ in columns])

        _autosize(ws)
        sheet_registry.append({"name": sheet_name, "rows": len(rows)})

    for entry in sheet_registry:
        row = summary_ws.max_row + 1

        name_cell = summary_ws.cell(row=row, column=1, value=_clean_excel_value(entry["name"]))
        name_cell.font = Font(bold=True)

        rows_cell = summary_ws.cell(row=row, column=2, value=_clean_excel_value(entry["rows"]))
        rows_cell.font = Font(italic=True)

    _autosize(summary_ws)

    if len(wb.sheetnames) == 1:
        summary_ws.append([])
        summary_ws.append(["No analytical data available."])

    stream = BytesIO()
    wb.save(stream)
    return stream.getvalue()
